### ISSUE TITLE
Missing links

### ISSUE THREAD

**Issue by technocrat** [harrelfe/rscripts#1]
[Section 3 of the R Workflow document](https://www.fharrell.com/post/rflow#analysis-file-creation) references [the Reproducible Research page](https://hbiostat.org/rr/index.html#template) which provides a download of `reportTemplate.qmd` which (I'm getting there) has

``require(Hmisc); getRs('kable.r', put='source')``

which returns a 404

``getRs('kable.r', put='source')
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection to 'https://github.com/harrelfe/rscripts/raw/master/kable.r'
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open URL 'https://github.com/harrelfe/rscripts/raw/master/kable.r': HTTP status was '404 Not Found'``

Totally fabulous trove. All praise.

**Comment by harrelfe** [comment]
Sorry to respond this late.  It appears to have been fixed a while ago.  Thanks for reporting.
